# Generated by Django 5.1.4 on 2025-01-04 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('scanning', models.CharField(max_length=255, verbose_name='Código de scanning')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('PP', 'Pastas y Panificados'), ('AL', 'Alimentos Lácteos y/o Vegetales'), ('HU', 'Huevos'), ('PC', 'Productos Congelados'), ('OT', 'Otros')], max_length=2, verbose_name='Grupo')),
                ('subgrupo', models.CharField(max_length=255, verbose_name='Subgrupo')),
                ('dias_retiro', models.PositiveIntegerField(verbose_name='Días para retiro')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de vencimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='controlapp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='controlapp.tipo'),
        ),
    ]
